
import sys
import os
from pathlib import Path

# Add src to path
sys.path.append(str(Path(__file__).parent.parent.parent))

from index.database import Database
from index.precision_search import PrecisionSearchEngine
from ai.client import AIClient
from synthesize.engine import SynthesisEngine
from deep_dx.config import get_deepdx_settings

deep_dx_settings = get_deepdx_settings()

# Mock imports for testing if environment is incomplete
from unittest.mock import MagicMock

def main():
    print("🏥 Starting Deep-DX Synthesis Engine Test...")
    
    # 1. Initialize Database
    # We use the existing DB if available, or create a dummy one for the test structure to pass
    db_path = Path("neurosynth.db") 
    print(f"📂 Database: {db_path}")
    db = Database(db_path=db_path)
    
    # 2. Check ColBERT status
    print("🦞 Initializing Precision Search (ColBERT)...")
    search_engine = PrecisionSearchEngine(db, colbert_enabled=True)
    if not search_engine.colbert: 
        print("⚠️  ColBERT Client failed to initialize.")
    else:
        print("✅ ColBERT Client initialized.")
        
    # 3. Initialize AI Client
    # We need to mock this if no keys are present to avoid crash, 
    # but we want to fail if keys are missing but expected.
    # For this test, let's mock the keys if missing so we can test the wiring.
    fake_key = "sk-fake-key"
    try:
        ai_client = AIClient()
    except ValueError:
        print("⚠️  No API Keys found. Using Mock AI Client for wiring test.")
        ai_client = MagicMock()
        ai_client.get_embedding.return_value = [0.1] * 768
        ai_client.synthesize_section.return_value = "This is a synthesized section about the facial nerve generated by the Deep-DX Mock AI."

    # 4. Initialize Synthesis Engine
    print("🧠 Initializing Synthesis Engine...")
    sythesis_engine = SynthesisEngine(
        db=db,
        search_engine=search_engine, # Passing PrecisionSearchEngine
        ai_client=ai_client
    )
    
    # 5. Run Synthesis
    topic = "Translabyrinthine approach for acoustic neuroma"
    print(f"🧪 Synthesizing Chapter: '{topic}'...")
    
    try:
        # We need at least some data in the DB or the mock AI to return chunks?
        # If DB is empty, search returns empty. 
        # Mocking retrieve_for_topic on the search engine?
        # No, let's let it run. If DB is empty it should gracefully handle "No content".
        
        chapter = sythesis_engine.synthesize_chapter(
            topic=topic,
            template_name="surgical_procedure"
        )
        
        print("\n✅ Synthesis Complete!")
        print(f"Title: {chapter.topic}")
        print(f"Total Sections: {len(chapter.sections)}")
        print(f"Sources Used: {len(chapter.sources)}")
        
        for section in chapter.sections:
            print(f"\n--- Section: {section.title} ---")
            print(f"Content Length: {len(section.content)} chars")
            print(f"Images: {len(section.images)}")
            print(f"Snippet: {section.content[:100]}...")
            
    except Exception as e:
        print(f"\n❌ Synthesis Failed: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main()
